### PR TITLE
JBIDE-22752: Enable GTK3 for vpe tests

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by ibuziuk** [comment]
@rawagner This change would affect all vpe tests - jsf / jsp engine does not work against GTK 3 due to the fact that required xulrunner is compiled only aginst gtk2 (gtk3 is supported only by vpv / html preview engine - those tests should work fine). Basically, all vpe tests would be simply skipped on Linux. One can test it by setting SWT_GTK3 =1 in tests/pom.xml

**Comment by rawagner** [comment]
ah, didnt notice the skipped tests :/ I've added property to disable/enable gtk3. Disabled by default, enabled only for vpv tests

**Comment by ibuziuk** [comment]
testPR

**Comment by ibuziuk** [comment]
@rawagner 2 failing tests on jenkins: 
**- org.jboss.tools.vpe.jst.angularjs.test.ca.AngularDynamicCATest.testControllerProperties**
**- org.jboss.tools.vpe.jst.angularjs.test.ca.AngularDynamicCATest.testControllers**
This is happening due to absence of webkit gtk2 libs on the slave (builds fine locally) - might be fixed by enabling gkt 3 for org.jboss.tools.vpe.jst.test. The bad thing is that vpv tests on linux are highly dependent on gtk + webkit libs availability (which we can not fully control)

**Comment by rawagner** [comment]
OK, lets try with gtk3 enabled for vpe.jst.test. PR updated

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
testPR

**Comment by ibuziuk** [comment]
testPR

**Comment by rawagner** [comment]
Shouldnt we setup a two jobs for checking PRs against VPE ? one which would be restricted to windows and another one to linux ?

**Comment by ibuziuk** [comment]
@dgolovin @nickboldt @rawagner  guys, really need your opinion about this PR. Basically, it was created due to the fact that visual html preview engine tests (#337) are failing on jenkins that verify vpe  pull requests - https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-vpe-Pull-Request/7/ This is happening due to the fact that linux slave has no webkitgtk2 libs installed. By applying this PR we assume that linux slave has libwebkitgtk3 libs and all vpv tests will be run against gtk 3 (vpe tests will still run against gtk 2). The problem is that we can not fully control webkit libs availability on the slave e.g. we will return to this issue again and again in different contexts. WDYT about configuring job for verifying vpe PRs so that it would run only against  mac os / windows ?

**Comment by rawagner** [comment]
@ibuziuk actually we control slaves on CentralCI and we make sure that every rhel7 slave has webkitgtk3 installed -  its scripted during slave provisioning.

**Comment by ibuziuk** [comment]
@rawagner great. So, this is another and probably the right option for tackling this issue. As I understand slaves on main jenkins http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-vpe_master/ are tuned so that webkitgtk libs are installed and all vpe / vpv tests are running against GTK 2 successfully. In this case I would propose to close this PR and have the same configuration for slaves that are used on main vpe jenkins

**Comment by rawagner** [comment]
@ibuziuk we tried that but problem is that rhel7 doesnt have webkit for GTK2 in repositories, only gtk3 version.

**Comment by ibuziuk** [comment]
@rawagner in this case I'm pretty baffled how tests are passing on the main http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-vpe_master/ 
I just want to make sure that if we apply this PR there will not be situation in which tests are passing on PR jenkins and failing on the main one

**Comment by rawagner** [comment]
@ibuziuk  main jenkins uses RHEL6 (which has webkit for gtk2).
By enabling SWT_GTK3 for some tests (as done is this PR) we should be able to run tests on RHEL7 (which has only libwebkit gtk3)and they should also work on RHEL6 (gtk2 will be used, SWT_GTK3=1 shouldnt make any difference ) afaik

**Comment by ibuziuk** [comment]
@rawagner the thing I can not understand is why after applying this PR vpv tests on RHEL 6 will be run against GTK 2 even with SWT_GTK3=1 enabled

**Comment by rawagner** [comment]
@ibuziuk im not really sure but i think that rhel6 doesnt have GTK3 libraries so SWT_GTK3 just doesnt have any effect

**Comment by rawagner** [comment]
Doesnt work on RHEL6. 
So the tests would fail on main jenkins (because it uses RHEL6) and work on CentralCI (due to RHEL7). 
After a discussion with @ibuziuk we think that we are ok with using only RHEL7 on both centralci and main jenkins. @nickboldt  would it be possible to use RHEL7 for this job http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-vpe_master/ ?

**Comment by ibuziuk** [comment]
@nickboldt @rawagner + 1 for using RHEL7 for main vpe jenkins. I really think it is a good idea to have the same setup for centralci and main jenkins. Should we create a separate jira for it ?

**Comment by nickboldt** [comment]
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-vpe_master/ has been moved to run on RHEL7 slaves only. See build 982 for the first one.

**Comment by ibuziuk** [comment]
testPR

**Comment by ibuziuk** [comment]
Thanks everyone. pushed to master

**Pull request merged**
