### PR TITLE
Removed XULRunner tests

### PR DESCRIPTION
**Pull request by jeffmaury**
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by jeffmaury** [comment]
@jkopriva Please review and test

**Comment by jkopriva** [comment]
@jeffmaury I have run it on Fedora and tests are ok.
@rawagner or @odockal can you please also review?

**Comment by odockal** [comment]
@jeffmaury Have you tried to to search for dependencies in other j.b.t. projects? I bet that ie. j.b.t.javaee project wont build as it has require-bundle to xulrunner package: https://github.com/jbosstools/jbosstools-javaee/blob/master/jsf/tests/org.jboss.tools.jsf.vpe.jsf.test/META-INF/MANIFEST.MF#L17. 

Also, many javaee.jsf unit tests were inheriting from VpeTest class (ie. https://github.com/jbosstools/jbosstools-javaee/blob/master/jsf/tests/org.jboss.tools.jsf.vpe.jsf.test/src/org/jboss/tools/jsf/vpe/jsf/test/jbide/XulRunnerVpeUtilsTest.java#L31) and when you are about to remove check for GTK3 (https://github.com/jbosstools/jbosstools-vpe/pull/352/commits/a03fc570dbd02a403709ebd634879774ee9e807f#diff-29b069831993f94df30a3e66a6e60e86L375) tests may start to fail instead of being skipped.

**Comment by jeffmaury** [comment]
@odockal Yes I'll start updating them as soon as this one is merged

**Comment by odockal** [comment]
@jeff great, will do review now.

**Comment by odockal** [comment]
@jeffmaury  Compilation & test went fine, there are just some warnings and some skipped tests (saw one), otherwise there are no errors nor failures. Could you squash the commits and add a signoff?

**Comment by rawagner** [comment]
@jeffmaury PR looks ok but if we push this, we have to fix all affected components before the codefreeze which is tomorrow. Do you think it is doable ?

**Comment by nickboldt** [comment]
Which components are affected, @rawagner  ?

**Comment by rawagner** [comment]
javaee - JSF and Seam. Seam is deprecated but it is still being build and is available on jbosstools update site.

**Pull request merged**
