### PR TITLE
JBIDE-23663: navigation buttons are not updated correctly when workin…

### PR DESCRIPTION
**Pull request by rawagner**
…g with multipage

Same as #347

### CODE REVIEW

**Comment by rawagner** [comment]
testPR

**Comment by ibuziuk** [comment]
testPR

**Comment by ibuziuk** [comment]
testPR

**Comment by ibuziuk** [comment]
testPR

**Comment by ibuziuk** [comment]
@rawagner Thanks! Rebased and pushed to master

**Pull request closed without merging**
