### PR TITLE
JBIDE-22681 Add tests for Vpv toolbar

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by alexeykazakov** [comment]
testPR

**Comment by alexeykazakov** [comment]
LGTM.
@ibuziuk please review and merge.

**Comment by ibuziuk** [comment]
@rawagner thanks, pushed to master. One thing I have noticed - there are several classes that miss copyright header. Could you please check this + several other PRs that you have provided recently and check / add required headers?

**Comment by rawagner** [comment]
@ibuziuk sure, thanks for noticing. I've created a JIRA https://issues.jboss.org/browse/JBIDE-22692. Will fix asap

**Comment by ibuziuk** [comment]
@rawagner thanks!

**Pull request merged**
